### ISSUE TITLE
Compatibility with OpenSSL 1.1.0 and FFMPEG 4.1

### ISSUE THREAD

**Issue by christofsteel** [gyunaev/karlyriceditor#1]
This does not compile anymore with openssl >= 1.1.0 because of how EVP_CIPHER_CTX is handled. (See https://stackoverflow.com/questions/26345175/correct-way-to-free-allocate-the-context-in-the-openssl)

Additionally libavresample was dropped from ffmpeg. As an alternative, there is libswresample, which acts as its replacement, but has a slightly different API.

**Comment by gyunaev** [comment]
Fixed by the 3.0 release.
