### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by Philippe593** [gyunaev/karlyriceditor#12]
Hi,

I'm trying to build the program but make stops very early on because of a qt multimedia dependency missing.
I suppose I'll get around to finding it at some point, but in the meantime, and for other users' sake, would it be possible to add a complete list of the build dependencies in the instructions ?

TIA.

**Comment by gyunaev** [comment]
"Stop very early" is not a bug report. Please provide the output.

**Comment by Philippe593** [comment]
There you go : 
`philippe@philippe-studio:~/git/karlyriceditor-3.2$ make
cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/philippe/git/karlyriceditor-3.2/src/src.pro ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: multimedia
make: *** [Makefile:47 : sub-src-make_first] Erreur 3
`

**Comment by gyunaev** [comment]
You'd need qt-multimedia-devel or however is it called on your distro. You'd also need ffmpeg-devel and openssl-devel.

**Comment by Philippe593** [comment]
After some research, the full shopping list on an Ubuntu distro would be : 
libavutil-dev
libavformat-dev
libavcodec-dev
openssl-dev
libswscale-dev
libswresample-dev
qtmultimedia5-dev
libqt5multimediawidgets5
libqt5multimedia5-plugins
libqt5multimedia5

And with all that on board it builds like a charm.

Thank you for your time.

**Comment by gyunaev** [comment]
Note that on some distros libav* and libsw* are generally part of ffmpeg-devel.
