### ISSUE TITLE
How to build for osx?

### ISSUE THREAD

**Issue by zenonasz** [gyunaev/karlyriceditor#15]
can someone point me to how to build this for osx?
the build-release file contains code for svn

Thanks

**Comment by gyunaev** [comment]
I never built it on OS X and it is likely gonna be major challenge; you'd need to build dependencies first.

**Comment by gyunaev** [comment]
Yeah, built-release builds it, but it doesn't build dependencies, which gonna be your major headache, especially `ffmpeg`.

Overall it is simple:
- Build all dependencies;
- Install Qt 5.15
- Build as standard Qt app (qmake && make)

Once you get past step 1, things gonna be easy. But the first step is a challenge, notably because `ffmpeg` itself requires a lot of dependencies.

**Comment by zenonasz** [comment]
> Yeah, built-release builds it, but it doesn't build dependencies, which gonna be your major headache, especially `ffmpeg`.
> 
> Overall it is simple:
> 
> * Build all dependencies;
> * Install Qt 5.15
> * Build as standard Qt app (qmake && make)
> 
> Once you get past step 1, things gonna be easy. But the first step is a challenge, notably because `ffmpeg` itself requires a lot of dependencies.

I have most of deps I think already, Qt as well, and will try to run the project. 


Basically, since you are the dev, I am here because I am looking to convert lrc file to UltraStar files. i was looking to see how you create and add breaks e.t.c. and how you parse and convert the timestamp of lrc into frames for UltraStar.

If you can point me to the files you handling the conversion i mention I will appreciate it. 

In any way, thanks for the prompt response

**Comment by gyunaev** [comment]
There's no direct converter (it imports them and exports them through an intermediate format) but what you want could be achieved through a simple Python script. No need to use this program, and you can use batch processing.

And if you only need one file converted, install a Windows/Linux VM (or run one on MS/AZN cloud) and run a binary, will be faster.
