### ISSUE TITLE
Audio truncated at the end when exporting to video

### ISSUE THREAD

**Issue by sraillard** [gyunaev/karlyriceditor#3]
I'm using the version 3.0 on Windows 10 64-bits. I have tested both versions (32-bits and 64-bits).
The problem is when exporting to video, the end of audio is muted.
Everything works fine when using the "test lyrics" button.

For example, with a MP3 of 3:20 duration, in the MP4 video file exported, the audio stops after 3:04, but the lyrics are still correctly displayed.

As a workaround, I have added some extra time to my MP3 file to have the full audio export.

**Comment by gyunaev** [comment]
Should be fixed in 3.1 release

**Comment by sraillard** [comment]
The issue is still present in version 3.1

**Comment by gyunaev** [comment]
Please provide a test case. It works for me.

**Comment by MrScottyTay** [comment]
I've just had this happen to me in 3.2, like a few seconds after the last lyrics it just gets cut off, video continues, but is stuck on the last frame and doesn't continue the music. Makes the song I'm doing unusable
