### ISSUE TITLE
Video output has no Audio

### ISSUE THREAD

**Issue by STLITGuy** [gyunaev/karlyriceditor#4]
When exporting using the export video file the resulting file has no audio.  I used the option of encode according to profile.  It appears that there is audio when viewing info about the video but it's not there when playing it back.  Info from FFMPEG below.  I tried on both windows and linux with the same results.

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'output.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:01:49.20, start: 0.000000, bitrate: 1595 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 1592 kb/s, 30.01 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: ac3 (ac-3 / 0x332D6361), 44100 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main

**Comment by gyunaev** [comment]
Which export settings did you use?
