### ISSUE TITLE
Unicode issues in file name and export LRC

### ISSUE THREAD

**Issue by bigboss97** [gyunaev/karlyriceditor#6]
1) I tried to import a Chinese MP3 in my project. It failed to load. I had to work around by renaming the file.
The editor has no problem in handling Chinese. I managed to create a CDG with Chinese lyric.
2) When I exported the Chinese lyric the characters in the file are corrupted.

**Comment by gyunaev** [comment]
1. Which version and which operating system?
2. Can you please share your project file? You can share it with or without music.

Regarding corrupted characters. When you click "Export CD+G file", then click on Preview tab and move the slider, does the screen show corrupted characters, or they are ok? If they are corrupted, did you try to change the font?

**Comment by bigboss97** [comment]
Thank you for the prompt response.

>     1. Which version and which operating system?
v3.2  on Windows 10.
>     2. Can you please share your project file? You can share it with or without music.
The project is fine (with the workaround in filename). Chinese characters appear in the editor and CDG view correctly. The exported CDG can be played in other player perfectly.
Only the exported LRC file is corrupted. I tried both Chinese Traditional encodings on import. All failed.
I guess the CDG is using unicode therefore no encoding specification is required. It even works on 3rd party player  :-)

**Comment by gyunaev** [comment]
CDG is using graphic rendering, so it can show anything at all.

Can you post an example of LRC file with Chinese lyrics which your karaoke player shows correctly? I'd like to see which encoding it uses. Have you tried UTF-8?

**Comment by bigboss97** [comment]
Yeah, it works with UTF-8. Thanks for your help  :-)
and what about the filename of a MP3 file while creating a project?

**Comment by gyunaev** [comment]
Probably needs some fixing too.

**Comment by bigboss97** [comment]
Maybe the import encoding should be defaulted to UTF-8.
The reason I did an export and import because I don't know how to replace the song with the vocal-less track in the project after synchronization. So I created a new project with the karaoke music and tried to import the lyrics  :-)

**Comment by gyunaev** [comment]
The song is not stored in the project, only the path to MP3 file is stored. You can change it to a new MP3 file in Project -> Project settings.

**Comment by bigboss97** [comment]
I couldn't find that settings and at the end I swapped the filenames hahaha
Thanks for pointing that out.
