### ISSUE TITLE
[Feature req] Allowing user to specify two audio files in one project

### ISSUE THREAD

**Issue by bigboss97** [gyunaev/karlyriceditor#7]
During lyric synchronization the vocal is required. But to export to CDG the instrumental version is required.
Proposal:
User can specify two audio files in one project and he can toggle between the files. So he can test lyrics with the instrumental file.

**Comment by gyunaev** [comment]
You can use the vocal file with your project, and use the instrumental file with the CDG/LRC file. The editor doesn't need the non-vocal file at all, unless you want to export video.

**Comment by bigboss97** [comment]
You are absolutely right.
I was only thinking to have a little bit fun while doing the boring synchronization. So I can do some test singing to motivate myself to complete the work  :-)
